### Get all users

GET http://localhost:3000/users

### Get a user

GET http://localhost:3000/users/65fa52e9fd40cf12697c3882

### Create user

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Joey",
    "age": 14
}

### Delete user

DELETE http://localhost:3000/users/65fb3816068d8b01ddcec9ee

### Update user

PATCH http://localhost:3000/users/65fa52e9fd40cf12697c3882
Content-Type: application/json

{
    "name": "Bob Ross",
    "age": 54
}
