### Get all restaurants
GET http://localhost:4000/restaurants

### Get a restaurant
GET http://localhost:4000/restaurants/65fd5d10aa3c5f39d245090d

### Create restaurant
POST http://localhost:4000/restaurants
Content-Type: application/json
{
    "name": "TEST",
    "location": "123 Main St",
    "rating": 4.5
}



### Delete restaurant
DELETE http://localhost:4000/restaurants/65fdadf91f347f6e6a2e9693

# ### Update restaurant


### Update restaurant soldOut
PATCH http://localhost:4000/restaurants/65fd5d10aa3c5f39d245090d/menu/65fd5d10aa3c5f39d245090e
Content-Type: application/json

{
    "soldOut": true
}




### Update restaurant soldOut
PATCH http://localhost:4000/restaurants/65fd5d10aa3c5f39d245090d/menu/65fd5d10aa3c5f39d245090e
Content-Type: application/json

{
    "soldOut": false
}



### Add item to restaurant's menu
POST http://localhost:4000/restaurants/65fdadf91f347f6e6a2e9693/menu
Content-Type: application/json
{
    "name": "IDK",
    "price": 2.99,
    "description": "Delicious burger with all the fixings",
    "soldOut": false
}

### Delete item from restaurant's menu
DELETE http://localhost:4000/restaurants/65fb3b8b8520f755e67b654f/menu/65fb47be3e10088a7aee221b

### Get a item from a restaurant
GET http://localhost:4000/restaurants/65fd5d10aa3c5f39d245090d/menu/65fd5d10aa3c5f39d245090e

### Get restaraunt's menu
GET http://localhost:4000/restaurants/65fd5d10aa3c5f39d245090d/menu
