### Get all users
GET http://localhost:4000/users

### Get a user
GET http://localhost:4000/users/65fa52e9fd40cf12697c3882

### Create user
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Customer",
    "age": 20,
    "username": "C",
    "password": "C",
    "role": "customer",
    "employed_for": "none"

}
### Create user
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Manager",
    "age": 25,
    "username": "M",
    "password": "M",
    "role": "manager",
    "employed_for": "Star Spot"
}


### Create user

POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Manager",
    "age": 25,
    "username": "M",
    "password": "M",
    "role": "manager",
    "employed_for": "Tasty Bites"
}

### Delete user
DELETE http://localhost:4000/users/66010d16aa0b53f0e146840c

### Update user
PATCH http://localhost:4000/users/65fa52e9fd40cf12697c3882
Content-Type: application/json
{
    "name": "Alex Ham",
    "age": 54,
    "username": "bobby",
    "password": "newpassword"
}